"""Initial migration with ENUM type fix

Revision ID: 6859080d1eaf
Revises: c3e82be1c6ae
Create Date: 2024-09-15 21:30:57.616981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6859080d1eaf'
down_revision = 'c3e82be1c6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupcakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large', name='cupcake_size'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupcakes')
    # ### end Alembic commands ###
