"""Initial migration

Revision ID: c3e82be1c6ae
Revises: 
Create Date: 2024-09-15 21:23:07.722576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e82be1c6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupcakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flavor', sa.String(), nullable=False),
    sa.Column('size', sa.Enum('small', 'medium', 'large'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupcakes')
    # ### end Alembic commands ###
